version: '3.3'
services:
  postgres:
    image: postgres:10
    container_name: java-pg
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"