version: "3.3"

services:
  postgres:
    image: postgres:10
    container_name: postgres-hibernate-demo
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: